import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['comfortaa', 'roboto', 'kaushan script'] });


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="icon" href="./img/favicon.ico" type="image/x-icon"></link>
      </head>

      <body className={inter.className}>{children}
      </body>
    </html>
  );
}
